// Real external origins this app actually loads content from -- keep this
// list in sync with what's really used (grepped src/ before writing this):
// Cloudinary (project photos/video, res.cloudinary.com), Google's keyless
// favicon service (press outlet icons, MediaGrid.jsx/Press.jsx -- the
// service itself is requested at www.google.com/s2/favicons but actually
// serves the icon bytes from *.gstatic.com, confirmed via a real
// Playwright run against this exact CSP, not assumed) and Google Maps'
// keyless embed (IndiaMapEmbed.jsx, an <iframe>). No analytics/ads/other
// third-party script ever loads here, so script-src stays 'self' (with
// 'unsafe-inline' only because Next.js's own streaming/hydration scripts
// are inline and this app doesn't use nonce-based CSP -- see below for
// why not).
const cspHeader = `
  default-src 'self';
  script-src 'self' 'unsafe-inline';
  style-src 'self' 'unsafe-inline';
  img-src 'self' blob: data: https://res.cloudinary.com https://www.google.com https://*.gstatic.com;
  media-src 'self' https://res.cloudinary.com;
  font-src 'self';
  frame-src https://www.google.com;
  connect-src 'self';
  object-src 'none';
  base-uri 'self';
  form-action 'self';
  frame-ancestors 'self';
  upgrade-insecure-requests;
`
  .replace(/\s{2,}/g, " ")
  .trim();

// A nonce-based CSP (dropping 'unsafe-inline' from script-src) is the
// stricter option, but per this Next.js version's own docs
// (node_modules/next/dist/docs/01-app/02-guides/content-security-policy.md)
// it requires every page to opt into dynamic rendering -- this site is
// static-generated by design (marketing pages, no per-request data), so
// that tradeoff isn't worth it here. This app also never renders
// user-submitted content back into the page (the contact form only ever
// sends data to /api/contact, nothing it collects is echoed into any
// page), which is the main scenario 'unsafe-inline' script-src actually
// exposes -- so the real risk this leaves open is low at this site's
// actual shape.
const securityHeaders = [
  { key: "Content-Security-Policy", value: cspHeader },
  { key: "X-Frame-Options", value: "SAMEORIGIN" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=()",
  },
  { key: "Strict-Transport-Security", value: "max-age=31536000" },
];

/** @type {import('next').NextConfig} */
const nextConfig = {
  /* config options here */
  devIndicators: false,
  images: {
    // Next.js 16 requires this allowlist explicitly -- AboutHero.jsx
    // requests quality={90} for its hero founder photos (S.png/P.png,
    // scaled up to ~3x via CSS transform), so 75 (the framework default)
    // alone isn't enough.
    qualities: [75, 90],
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: securityHeaders,
      },
    ];
  },
};

export default nextConfig;
