import { Geist, Geist_Mono, Inter, Fraunces } from "next/font/google";
import localFont from "next/font/local";
import Preloader from "@/components/Preloader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
});

const juana = localFont({
  src: [
    {
      path: "../fonts/juana-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/juana-medium.otf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-juana",
});

const agatho = localFont({
  src: "../fonts/agatho-regular.otf",
  weight: "400",
  style: "normal",
  variable: "--font-agatho",
});

const corporate = localFont({
  src: "../fonts/corporate-regular.otf",
  weight: "400",
  style: "normal",
  variable: "--font-corporate",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${fraunces.variable} ${juana.variable} ${agatho.variable} ${corporate.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Preloader />
        {children}
      </body>
    </html>
  );
}
